# coding: utf-8


OUTPUT_DIR = "output"
LOG_DIR = "logs"
MAX_WORKERS = 6

# don't modify position
NODE_LABELS = [
    "ANNOTATION",
    "BINDING",
    "BLOCK",
    "CALL",
    "CLOSURE_BINDING",
    "COMMENT",
    "CONTROL_STRUCTURE",
    "FIELD_IDENTIFIER",
    "FILE",
    "IDENTIFIER",
    "JUMP_TARGET",
    "LITERAL",
    "LOCAL",
    "MEMBER",
    "META_DATA",
    "METHOD",
    "METHOD_PARAMETER_IN",
    "METHOD_PARAMETER_OUT",
    "METHOD_REF",
    "METHOD_RETURN",
    "MODIFIER",
    "NAMESPACE",
    "NAMESPACE_BLOCK",
    "RETURN",
    "TAG",
    "TYPE",
    "TYPE_ARGUMENT",
    "TYPE_DECL",
    "TYPE_PARAMETER",
    "TYPE_REF",
    "UNKNOWN",
]

# GRAPH_TYPES = ["AST", "LastUse", "ComputedFrom"]
# 去AST方案
# GRAPH_TYPES = ["LastUse", "ComputedFrom", "CFG", "CDG", "PDG"]

GRAPH_TYPES = ["AST", "LastUse", "ComputedFrom", "CFG", "CDG", "DDG"]

# Pg-vulnet
# GRAPH_TYPES = ["AST", "CFG", "CDG", "DDG"]


MODEL = 'GMN' # {GMN, GAT}

# disjoint 考虑了边的类型
# GRAPH_MODE = 'disjoint' # {single, disjoint}
GRAPH_MODE = 'single'
# GRAPH_MODE = 'new_disjoint'

# # 是否使用高亮方案
HIGHLIGHT = False

GRAPH_DOT_FILES = {
    "AST.dot": "AST", 
    "LastUse.dot": "LastUse",
    "ComputedFrom.dot": "ComputedFrom",
    "CDG.dot": "CDG", 
    "DDG.dot": "DDG", 
    "CFG.dot": "CFG",
}

# pg-vulnet
# GRAPH_DOT_FILES = {
#     "AST.dot": "AST", 
#     "CDG.dot": "CDG", 
#     "DDG.dot": "DDG", 
#     "CFG.dot": "CFG",
# }


DOT_NODE_ATTR = 'label'

# donot modify it
MAP_DOT_LABEL = {
    "ANNOTATION": 0,
    "ANNOTATION_LITERAL": 1,
    "ANNOTATION_PARAMETER": 2,
    "ANNOTATION_PARAMETER_ASSIGN": 3,
    "ARRAY_INITIALIZER": 4,
    "BINDING": 5,
    "BLOCK": 6,
    "CALL": 7,
    "CALL_IN": 8,
    "CALL_OUT": 9,
    "CLOSURE_BINDING": 10,
    "COMMENT": 11,
    "CONFIG_FILE": 12,
    "CONTROL_STRUCTURE": 13,
    "DEPENDENCY": 14,
    "DETACHED_TRACKING_POINT": 15,
    "DOM_ATTRIBUTE": 16,
    "DOM_NODE": 17,
    "FIELD_IDENTIFIER": 18,
    "FILE": 19,
    "FINDING": 20,
    "FRAMEWORK": 21,
    "FRAMEWORK_DATA": 22,
    "IDENTIFIER": 23,
    "IMPLICIT_CALL": 24,
    "JUMP_TARGET": 25,
    "KEY_VALUE_PAIR": 26,
    "LITERAL": 27,
    "LOCAL": 28,
    "LOCATION": 29,
    "MEMBER": 30,
    "META_DATA": 31,
    "METHOD": 32,
    "METHOD_INST": 33,
    "METHOD_PARAMETER_IN": 34,
    "METHOD_PARAMETER_OUT": 35,
    "METHOD_REF": 36,
    "METHOD_RETURN": 37,
    "MODIFIER": 38,
    "NAMESPACE": 39,
    "NAMESPACE_BLOCK": 40,
    "OPERATOR": 41,
    "PACKAGE_PREFIX": 42,
    "POST_EXECUTION_CALL": 43,
    "RETURN": 44,
    "SINK": 45,
    "SOURCE": 46,
    "TAG": 47,
    "TAGS": 48,
    "TAG_NODE_PAIR": 49,
    "TYPE": 50,
    "TYPE_ARGUMENT": 51,
    "TYPE_DECL": 52,
    "TYPE_PARAMETER": 53,
    "TYPE_REF": 54,
    "UNKNOWN": 55
}

NODE_LABELS_DOT = [
    "ANNOTATION",
    "ANNOTATION_LITERAL",
    "ANNOTATION_PARAMETER",
    "ANNOTATION_PARAMETER_ASSIGN",
    "ARRAY_INITIALIZER",
    "BINDING",
    "BLOCK",
    "CALL",
    "CLOSURE_BINDING",
    "COMMENT",
    "CONFIG_FILE",
    "CONTROL_STRUCTURE",
    "DEPENDENCY",
    "DETACHED_TRACKING_POINT",
    "DOM_ATTRIBUTE",
    "DOM_NODE",
    "FIELD_IDENTIFIER",
    "FILE",
    "FINDING",
    "FRAMEWORK",
    "FRAMEWORK_DATA",
    "IDENTIFIER",
    "IMPLICIT_CALL",
    "JUMP_TARGET",
    "KEY_VALUE_PAIR",
    "LITERAL",
    "LOCAL",
    "LOCATION",
    "MEMBER",
    "META_DATA",
    "METHOD",
    "METHOD_INST",
    "METHOD_PARAMETER_IN",
    "METHOD_PARAMETER_OUT",
    "METHOD_REF",
    "METHOD_RETURN",
    "MODIFIER",
    "NAMESPACE",
    "NAMESPACE_BLOCK",
    "PACKAGE_PREFIX",
    "POST_EXECUTION_CALL",
    "RETURN",
    "SINK",
    "SOURCE",
    "TAG",
    "TAGS",
    "TAG_NODE_PAIR",
    "TYPE",
    "TYPE_ARGUMENT",
    "TYPE_DECL",
    "TYPE_PARAMETER",
    "TYPE_REF",
    "UNKNOWN"
]

OPERATOR_LABEL = [
    "<operator>.addition",
    "<operator>.addressOf",
    "<operator>.and",
    "<operator>.arithmeticShiftRight",
    "<operator>.assignment",
    "<operator>.assignmentDivision",
    "<operator>.assignmentMinus",
    "<operator>.assignmentMultiplication",
    "<operator>.assignmentPlus",
    "<operator>.cast",
    "<operator>.compare",
    "<operator>.computedMemberAccess",
    "<operator>.conditional",
    "<operator>.delete",
    "<operator>.division",
    "<operator>.equals",
    "<operator>.exponentiation",
    "<operator>.fieldAccess",
    "<operator>.getElementPtr",
    "<operator>.greaterEqualsThan",
    "<operator>.greaterThan",
    "<operator>.indexAccess",
    "<operator>.indirectComputedMemberAccess",
    "<operator>.indirectFieldAccess",
    "<operator>.indirectIndexAccess",
    "<operator>.indirectMemberAccess",
    "<operator>.indirection",
    "<operator>.instanceOf",
    "<operator>.lessEqualsThan",
    "<operator>.lessThan",
    "<operator>.logicalAnd",
    "<operator>.logicalNot",
    "<operator>.logicalOr",
    "<operator>.logicalShiftRight",
    "<operator>.memberAccess",
    "<operator>.minus",
    "<operator>.modulo",
    "<operator>.multiplication",
    "<operator>.not",
    "<operator>.notEquals",
    "<operator>.or",
    "<operator>.plus",
    "<operator>.pointerShift",
    "<operator>.postDecrement",
    "<operator>.postIncrement",
    "<operator>.preDecrement",
    "<operator>.preIncrement",
    "<operator>.shiftLeft",
    "<operator>.sizeOf",
    "<operator>.subtraction",
    "<operator>.xor",
    "<operators>.assignmentAnd",
    "<operators>.assignmentArithmeticShiftRight",
    "<operators>.assignmentExponentiation",
    "<operators>.assignmentLogicalShiftRight",
    "<operators>.assignmentModulo",
    "<operators>.assignmentOr",
    "<operators>.assignmentShiftLeft",
    "<operators>.assignmentXor"
]

C_BUILT_IN_FUNCS = [
    "abort",
    "abs",
    "acos",
    "asctime",
    "asctime_r",
    "asin",
    "assert",
    "atan",
    "atan2",
    "atexit",
    "atof",
    "atoi",
    "atol",
    "atoll",
    "bsearch",
    "btowc",
    "_C_Get_Ssn_Handle",
    "calloc",
    "catclose",
    "catgets",
    "catopen",
    "ceil",
    "clearerr",
    "clock",
    "cos",
    "cosh",
    "_C_Quickpool_Debug",
    "_C_Quickpool_Init",
    "_C_Quickpool_Report",
    "ctime",
    "ctime64",
    "ctime_r",
    "ctime64_r",
    "_C_TS_malloc_debug",
    "_C_TS_malloc_info",
    "difftime",
    "difftime64",
    "div",
    "erf",
    "erfc",
    "exit",
    "exp",
    "fabs",
    "fclose",
    "fdopen",
    "feof",
    "ferror",
    "fflush",
    "fgetc",
    "fgetpos",
    "fgets",
    "fgetwc",
    "fgetws",
    "fileno",
    "floor",
    "fmod",
    "fopen",
    "fprintf",
    "fputc",
    "_fputchar",
    "fputs",
    "fputwc",
    "fputws",
    "fread",
    "free",
    "freopen",
    "frexp",
    "fscanf",
    "fseek",
    "fseeko",
    "fsetpos",
    "ftell",
    "ftello",
    "fwide",
    "fwprintf",
    "fwrite",
    "fwscanf",
    "gamma",
    "_gcvt",
    "getc",
    "getchar",
    "getenv",
    "_GetExcData",
    "gets",
    "getwc",
    "getwchar",
    "gmtime",
    "gmtime64",
    "gmtime_r",
    "gmtime64_r",
    "hypot",
    "isalnum",
    "isxdigit",
    "isascii",
    "iswalnum",
    "iswxdigit",
    "iswctype",
    "_itoa",
    "labs",
    "llabs",
    "ldexp",
    "ldiv",
    "lldiv",
    "localeconv",
    "localtime",
    "localtime64",
    "localtime_r",
    "localtime64_r",
    "log",
    "log10",
    "_ltoa",
    "longjmp",
    "malloc",
    "mblen",
    "mbrlen",
    "mbrtowc",
    "mbsinit",
    "mbsrtowcs",
    "mbstowcs",
    "mbtowc",
    "memchr",
    "memcmp",
    "memcpy",
    "memicmp",
    "memmove",
    "memset",
    "mktime",
    "mktime64",
    "modf",
    "nextafter",
    "nextafterl",
    "nexttoward",
    "nexttowardl",
    "nl_langinfo",
    "perror",
    "pow",
    "printf",
    "putc",
    "putchar",
    "putenv",
    "puts",
    "putwc",
    "putwchar",
    "quantexpd32",
    "quantexpd64",
    "quantexpd128",
    "quantized32",
    "quantized64",
    "quantized128",
    "qsort",
    "QXXCHGDA",
    "QXXDTOP",
    "QXXDTOZ",
    "QXXITOP",
    "QXXITOZ",
    "QXXPTOD",
    "QXXPTOI",
    "QXXRTVDA",
    "QXXZTOD",
    "QXXZTOI",
    "raise",
    "rand",
    "rand_r",
    "_Racquire",
    "_Rclose",
    "_Rcommit",
    "_Rdelete",
    "_Rdevatr",
    "realloc",
    "regcomp",
    "regerror",
    "regexec",
    "regfree",
    "remove",
    "rename",
    "rewind",
    "_Rfeod",
    "_Rfeov",
    "_Rformat",
    "_Rindara",
    "_Riofbk",
    "_Rlocate",
    "_Ropen",
    "_Ropnfbk",
    "_Rpgmdev",
    "_Rreadd",
    "_Rreadf",
    "_Rreadindv",
    "_Rreadk",
    "_Rreadl",
    "_Rreadn",
    "_Rreadnc",
    "_Rreadp",
    "_Rreads",
    "_Rrelease",
    "_Rrlslck",
    "_Rrollbck",
    "_Rupdate",
    "_Rupfb",
    "_Rwrite",
    "_Rwrited",
    "_Rwriterd",
    "_Rwrread",
    "samequantumd32",
    "samequantumd64",
    "samequantumd128",
    "scanf",
    "setbuf",
    "setjmp",
    "setlocale",
    "setvbuf",
    "signal",
    "sin",
    "sinh",
    "snprintf",
    "sprintf",
    "sqrt",
    "srand",
    "sscanf",
    "strcasecmp",
    "strcat",
    "strchr",
    "strcmp",
    "strcmpi",
    "strcoll",
    "strcpy",
    "strcspn",
    "strdup",
    "strerror",
    "strfmon",
    "strftime",
    "stricmp",
    "strlen",
    "strncasecmp",
    "strncat",
    "strncmp",
    "strncpy",
    "strnicmp",
    "strnset",
    "strset",
    "strpbrk",
    "strptime",
    "strrchr",
    "strspn",
    "strstr",
    "strtod",
    "strtof",
    "strtold",
    "strtod32",
    "strtod64",
    "strtod128",
    "strtok",
    "strtok_r",
    "strtol",
    "strtoll",
    "strtoul",
    "strtoull",
    "strxfrm",
    "swprintf",
    "swscanf",
    "system",
    "tan",
    "tanh",
    "time",
    "time64",
    "tmpfile",
    "tmpnam",
    "toascii",
    "tolower",
    "toupper",
    "towctrans",
    "towlower",
    "towupper",
    "_ultoa",
    "ungetc",
    "ungetwc",
    "va_arg",
    "va_copy",
    "va_end",
    "va_start",
    "vfprintf",
    "vfscanf",
    "vfwprintf",
    "vfwscanf",
    "vprintf",
    "vscanf",
    "vsnprintf",
    "vsprintf",
    "vsscanf",
    "vswprintf",
    "vswscanf",
    "vwprintf",
    "vwscanf",
    "wcrtomb",
    "wcscat",
    "wcschr",
    "wcscmp",
    "wcscoll",
    "wcscpy",
    "wcscspn",
    "wcsftime",
    "__wcsicmp",
    "wcslen",
    "wcslocaleconv",
    "wcsncat",
    "wcsncmp",
    "wcsncpy",
    "__wcsnicmp",
    "wcspbrk",
    "wcsptime",
    "wcsrchr",
    "wcsrtombs",
    "wcsspn",
    "wcsstr",
    "wcstod",
    "wcstof",
    "wcstold",
    "wcstod32",
    "wcstod64",
    "wcstod128",
    "wcstok",
    "wcstol",
    "wcstoll",
    "wcstombs",
    "wcstoul",
    "wcstoull",
    "wcswcs",
    "wcswidth",
    "wcsxfrm",
    "wctob",
    "wctomb",
    "wctrans",
    "wctype",
    "wcwidth",
    "wfopen",
    "wmemchr",
    "wmemcmp",
    "wmemcpy",
    "wmemmove",
    "wmemset",
    "wprintf",
    "wscanf",
    "j0",
    "j1",
    "jn",
    "y0",
    "y1",
    "yn",
]
